version: "3"
services:
  client:
    image: phygan/multi-client
    mem_limit: 128m
    hostname: client
  server:
    image: phygan/multi-server
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGHOST=$PGHOST
      - PGPORT=$PGPORT
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGDATABASE=$PGDATABASE
  worker:
    image: phygan/multi-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    depends_on:
      - server
      - client
    image: phygan/multi-nginx
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
