name: Deploy Multishizzle
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD}}
      - run: docker build -t phygan/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true phygan/react-test npm test

      - run: docker build -t phygan/multi-client-github ./client
      - run: docker build -t phygan/multi-nginx-github ./nginx
      - run: docker build -t phygan/multi-server-github ./server
      - run: docker build -t phygan/multi-worker-github ./worker

      - run: docker push phygan/multi-client-github
      - run: docker push phygan/multi-nginx-github
      - run: docker push phygan/multi-server-github
      - run: docker push phygan/multi-worker-github

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multidocker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-664435994406
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
